server:
    port: 8888
spring:
    application:
        name: newspace
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/toutiao?serverTimezone=UTC&userUnicode=true&useSSL=false&
        username: root
        password: j1101714214
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

#mybatis:
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
    secret: "toutiao"


